# Usage:
#   Baseline without tags:
#
#   $ ansible-playbook test_tags.yaml
#
#   Running with tags:
#
#   $ ansible-playbook test_tags.yaml
#
# idgaf what you do with it license, but prs are welcome
- name: Test Tags
  hosts: "localhost"
  tasks:
    - name: Foo
      debug:
        msg: "foo"
      tags:
        - foo

    - name: Import Bar_Tags Not Untagged
      import_tasks: bar_tags.yaml

    - name: Include Bar_Tags
      include_tasks: bar_tags.yaml
      tags:
        - bar

    - name: Import Bar_Tags
      import_tasks: bar_tags.yaml
      tags:
        - bar

    - name: Include Bar
      include_tasks: bar.yaml
      tags:
        - bar

    - name: Import Bar
      import_tasks: bar.yaml
      tags:
        - bar

    #
    # Tags do not inherit on the following:
    #

    - name: Include Bar_Tags Untagged - FAIL
      include_tasks: bar_tags.yaml


    - name: Include Bar Untagged - FAIL
      include_tasks: bar.yaml

    - name: Import Bar Untagged - FAIL
      import_tasks: bar.yaml
